### ISSUE TITLE
border没有改写。。

### ISSUE THREAD

**Issue by zhang0ZGC** [Spikef/postcss-weex#2]
`border: solid 1px #dddddd;`
weex出来还是
`"border": "solid 1px #dddddd"`

margin是可以的

**Comment by Spikef** [comment]
![image](https://user-images.githubusercontent.com/7875897/36713792-41b6015a-1bca-11e8-8483-324073a66585.png)

**Comment by zhang0ZGC** [comment]
抱歉，新版本里面有个usePostCSS没有设为true，设为true转换了
